# Site settings
title: Rapid Array
email: scott@rapidarray.net
description: > # this means to ignore newlines until "baseurl:"
  Rapid Array
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: 
github_username:  scottmcdowell
timezone: America/New_York

# Build settings
markdown: kramdown
